---
name: integration

"on":
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: integration-${{ github.ref }}
  cancel-in-progress: true

jobs:
  integration-linux:
    runs-on: ubuntu-latest
    name: Kitchen Verify
    strategy:
      matrix:
        ruby: ["3.3"]
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Create & Validate containers
        run: |
          bundle exec bundle exec kitchen create hello
          bundle exec bundle exec kitchen test helloagain
          bundle exec bundle exec kitchen destroy hello
        env:
          CHEF_LICENSE: "accept-no-persist"
