---
name: lint

"on":
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  chefstyle:
    env:
      BUNDLE_WITH: ${{ inputs.bundle_with }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.3"]
    name: Chefstyle on Ruby
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check for Gemfile
        id: check
        run: |
          if [ -f Gemfile ]; then
           echo "gemfile=true" >> $GITHUB_OUTPUT
          else
            echo "gemfile=false" >> $GITHUB_OUTPUT
          fi
      - name: Setup Ruby
        if: steps.check.outputs.gemfile == 'true'
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - uses: r7kamura/rubocop-problem-matchers-action@v1
        if: steps.check.outputs.gemfile == 'true'
      - name: Chef Style
        if: steps.check.outputs.gemfile == 'true'
        run: bundle exec chefstyle

  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run yaml Lint
        uses: actionshub/yamllint@main

  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Markdown lint
        uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          globs: "**/*.md"

  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gaurav-nelson/github-action-markdown-link-check@1.0.15
        with:
          use-quiet-mode: "yes"
          use-verbose-mode: "yes"
          check-modified-files-only: "yes"
          base-branch: "main"
